version: '3.4'
services:
  netbox:
    image: netbox:latest-plugins
    ports:
      - 8000:8080
    build:
      context: .
      dockerfile: Dockerfile-Plugins
    volumes:
      - ./wwt_plugin:/opt/netbox/netbox/wwt_plugin
  netbox-worker:
    image: netbox:latest-plugins
    build:
      context: .
      dockerfile: Dockerfile-Plugins
    volumes:
      - ./wwt_plugin:/opt/netbox/netbox/wwt_plugin
  netbox-housekeeping:
    image: netbox:latest-plugins
    build:
      context: .
      dockerfile: Dockerfile-Plugins
    volumes:
      - ./wwt_plugin:/opt/netbox/netbox/wwt_plugin
